#!/usr/bin/python
# vim: set fileencoding=utf-8 :
#
# © 2012–2015 Will Thompson <will@willthompson.co.uk>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os.path
import sys
import tempfile

from gi.repository import Gtk

from rebuilder import Rebuilder
from markdownview import MarkdownView

class ViewerWindow(Gtk.Window):
    def __init__(self, md_filename, html_filename):
        Gtk.Window.__init__(self)

        self.set_default_size(768, 600)

        self.filename = md_filename

        self.markdownview = MarkdownView(url=('file://' + html_filename))
        self.markdownview.connect('title_changed', self.__title_changed_cb)
        self.add(self.markdownview)

        self.rebuilder = Rebuilder(self.filename, html_filename)
        self.rebuilder.connect('rebuilt', self.__rebuilt_cb)
        self.rebuilder.rebuild()

        self.show_all()

    def __rebuilt_cb(self, rebuilder):
        self.markdownview.refresh()

    def __title_changed_cb(self, view, title):
        if title is None:
            title = self.filename
        else:
            title = '%s (%s)' % (title, self.filename)

        self.set_title(title)

if __name__ == '__main__':
    md_filename = os.path.realpath(sys.argv[1])
    with tempfile.NamedTemporaryFile(prefix=os.path.basename(md_filename), suffix='.html') as f:
        window = ViewerWindow(md_filename, f.name)
        window.connect('destroy', Gtk.main_quit)
        Gtk.main()
